### ISSUE TITLE
User Feedback

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#192]
(original document: [EVAL APP REVIEW.docx](https://github.com/PushTracker/EvalApp/files/2337018/EVAL.APP.REVIEW.docx) )

Brandon and I reviewed the Smart Drive Evalulation app today.  We evaluated the app for about 2 hours at Barton Creek mall on a carpeted surface.  We reviewed the turtorials/videos and then Brandon and I both took turns doing trials with and without the Smart Drive.  For each trial we did the same track, approximately.  

### RESULTS/COMMENTS:
---
- [x] The videos/tutorials are helpful resources and should also be included into the PushTracker app
- [x] The “Connectivity” title may be better titled “How to Connect” or “Connectivity Overview”.  This would help differentiate whether the app is actually connected vs how does one connect to the various devices ( https://github.com/PushTracker/EvalApp/commit/aab88c728fc7ba9b2c2767756305c588ff092adb )
- [x] On the topic of connectivity, there is no indication that the Eval app has to be paired to the pushtracker except for when you try to start a trial and it asks for you to pair.  This can be confusing also for the reason that there are 2 apps and one might think (as we did) that you pair to PushTracker app and that talks to SmartDrive Eval app (#251)
  - [x] Can add a button for tips/directions (#251 )

- [x] When referring to the “app” it may be better to include what “app” is being referred to (e.g. pushtracker, eval, both?) (https://github.com/PushTracker/EvalApp/commit/396ef51b13ebf27821f2af44dffb1ac00c77caa4)
- [x] Add somewhere to have only one app open at a time (https://github.com/PushTracker/EvalApp/commit/5b9cc372b9c9eb463fb0bd57d2b1a4e4c359bcf2)
- [x] There is the goal of getting rid of the PushTracker App
- [x] The tracking feature is great.  It could be improved if the GPS was more descriptive or included a map with pins or both? ( #185 )
- [x] The sliders for speed and accuracy are difficult to move because you have to hold it down and then slide.  It makes sense because if you swipe quickly it changes the page, but is there a more intuitive option or ability to decrease the sensitivity? (#284)
- [x] If you don’t complete a trial completely you lose the information you did complete.  Is there a way for this to save in the app as you work through it so you don’t have to start over if a trial fails or is completed for some reason (#190 )
- [x] Is there a maximum distance the evaluator can be away from the user without losing the connection? (https://github.com/PushTracker/EvalApp/commit/307513aae127ad116cffcc2d2883685b7ba51bc2)
- [x] The push counting is very inaccurate.  We pushed and didn’t push the PushTracker counts weren’t close.  For example, with the SmartDrive on and performing no pushes it recorded 4-5 pushes (maybe these were the taps?) and without the SmartDrive when we pushed 25-30 times it only recorded 14-17 pushes **(handled by PushSettings #186 and version 1.6 of the PushTracker Firmware)**
- [x] The coast time metric is a little confusing and also will be inaccurate if the push tracking is inaccurate. The coast time is defined as the amount of time the push drive is engaged divided by the amount of pushes performed during the time the push drive is engaged.  Should anyone really be pushing while the Smart Drive is engaged? (#241 )
- [x] The app measures distance in meters.  Should we change this to feet since this is the US market?
- [x] Is there any way to save the trials locally within the app (aside from sending the email) ( #191 )
- [x] Is there a way to identify each trial without using user identifiers.  For example, can the email have a time and date stamp?  Are we concerned at all about clinicians using identifiers or is that their concern?
- [x] It would be helpful to have a “next” button or some cue to move to the next screen during the trial (https://github.com/PushTracker/EvalApp/commit/18454ad5027ce2e88ea91a61317db1b3d02a32d2)
- [x] Out of 8 attempted total trials we had an issue starting 2-3 times when connected (timeout!) and 1 time stopping (resulting in us having to exit the trial completely and losing the rest of the data, see bullet 7)
- [x] Starting and stopping the trial takes about 10 s.  For a user this may seem like its taking too long or not working.  Can this be improved? If not can we use a timer to let the user know its moving towards completion or some other way to notify them (https://github.com/PushTracker/EvalApp/commit/963ac538d2173ae8a71d45965ecf2a6570a1d03a)

### Feedback Update 2018-11-01
- [x] The push tracker settings adjustments don't seem to be working well at all. Don't match Push tracker even if you click OK. You can make changes and hit save . Exit and go back in and nothing has changed. (#280 )
- [x] Also email opens but quickly crashes after completing Eval but works fine after you go back to saved evaluations. Then it emails out fine. (#282)
- [x] The summary when you rate ramp and incline difficulty needs to have an unable to complete ramp or incline when the slider hits 10. (#281)
- [x] Ramps/ inclines I believe should be one . (#283)

**Comment by finger563** [comment]
We will need to go through this and determine what issues / changes need to be addressed (that aren't already issues)

**Comment by finger563** [comment]
More feedback from Brandon: 

First chance to play this week. This pops up all the time even during trial. The push tracker settings adjustments don't seem to be working well at all. Don't match Push tracker even if you click OK. You can make changes and hit save . Exit and go back in and nothing has changed. 
Also email opens but quickly crashes after completing Eval but works fine after you go back to saved evaluations. Then it emails out fine. 

Changing PT settings in the Trial part worked though and the advice of 3/15 for me was SPOT ON in counting my pushes !! I mean really spot on. 
I also saw that it looks like we fixed the distance to be equal to the with SD total on the without automatically. 

The summary when you rate ramp and incline difficulty needs to have an unable to complete ramp or incline when the slider hits 10. 

Also ramps/ inclines I believe should be one .

**Comment by finger563** [comment]
Now that all of these tasks have been either completed or addressed by other (linked) issues, I will close this issue.
