### ISSUE TITLE
Beta Feedback

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#293]
- [x] ~The name of the app is “Smart Evaluation”.  When you look at the icon before selecting it, this can be confusing because “Permobil Smart Evaluation”.  I think the name/title of the app needs to have SmartDrive in it somewhere or else it looks like it is an evaluation app for Permobil (which is still synonymous with our power product line).~ 
 

- [x] For Android, while in the “Begin SmartDrive Evaluation” section, there was a small error when attempting to get back to the  SEA home page? When I attempted to use the back button to navigate back, the screen went white and another time it went back to a previous evaluation.
 

- [x] Had the screen go white 2-3 times when using the back button.  Hitting the back button again resolved it.
 

- [x] Excited that we have the Evaluations tab for previous evals!  It looks as if the eval tab includes trials too.  Can we title this Evaluation and Trials?
 

- [x] ~We should move the questionnaire page into the trial section too, so we can know more about the trial and collect more data~
 

- [x] ~I’m not sure if it is too late to talk about this, but I wanted to suggest moving “stopping” to the same section as “starting” in the training section under clinical tools and include to instruct starting and stopping before coasting.  It has been my experience that trials are more successful when you teach the user to start and stop at the same time multiple times prior to having them move on to more advanced movements.  Knowing how to stop is a pre-cursor to controlling the device in more complex ways, and then setting the speed is a skill built on to that.  This should include language similar to “have your client start and stop 5 times in front of you prior to training how to set the speed”~
 

- [x] Add mounting instructions to the general overview section (#294 )
 

- [x] For chair make, can we include folding vs. rigid? (#295)
 

- [x] “Starting & Setting Speed” include that the motor will accelerate up to max speed if no single tap is performed? (#294 )
 

- [x] “Turning” include that if you don’t have good grip strength you may need to disengage the motor to make shape turns (#294 )
 

- [x] “Stopping” include/highlight that a double tap only stops the motor, you must use your hands to stop the chair from moving (#294 )
 

- [x] Is it possible to give pairing and connecting instructions in a trial without exiting to the home screen.  Maybe not the entire set of instructions, but a window that has an image to help the user remember.  (#301 )
 

- [x] Difficulty on flat surface question at the end, should we try to capture type of surface (e.g. carpet)
 

- [x] “User difficulty” lines shouldn’t be included in LMN export, currently reporting 0/10.  Not entering an answer at the beginning of the trial could mean that the trial course didn’t include it and not because they are or aren’t able to do it. 
 

- [x] When I select complete it automatically leaves the app and opens my email with the draft LMN. I don’t think this is a problem, but during 2/3 attempts to return to the app using the app switcher, the Smartdrive app was still on the trial screen (where the complete button is) vs being at the home page. 
 

- [x] What is a clear counter?
 

- [x] ~On the LMN, the distance is only reported for one time and it appears to be using the “with SmartDrive” trial.  I think we should have the distance reported for both with and without SmartDrive trials.~
 

- [x] ~My trials are recording coast times for the without SmartDrive trials.  If the SmartDrive is  not engaged, shouldn’t the coast time be zero?  My SmartDrive did not engage during any of my without trials.~
 

- [x] PUSH COUNT:  At this point I have done about 7-8 trials.  Each trial had anywhere from 15-22 actual pushes, and the app was correct within +/- 2-3.
